spring:
  application:
    name: Task Management API
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:P@ssw0rd123}
    hikari:
      maximum-pool-size: 10       # default: 10
      minimum-idle: 5             # default: same as max
      idle-timeout: 300000        # 5 minutes
      connection-timeout: 30000   # 30 seconds
      max-lifetime: 1800000       # 30 minutes
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true


logging:
  config: classpath:log4j2-local.xml
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

server:
  port: 9999
  servlet:
    context-path: /api/v1/task-management